### ISSUE TITLE
Smooth tab edges

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/ATTabs#18]
@vhanla Can i ask you for this task?
work not on CudaText repo yet- but on ATTabs repo.
what we need: smooth edged tabs.
e.g. Sublime/Atom has them.
how to do:

- take repo ATTabs
- make new demo which uses ATTabs
- add events: OnTabDraw***
- in these events - add code to paint smooth edges. We need some kind of PNG pics, which will be painted
a) at left edge /----
b) at right edge ----\
c) at middle ------ to make smooth top edge

- lets use some fixed tab height (PNG pics must be for fixed height)
- tab width _not_ fixed
- prop OptShowAngled value- lets use false

**Comment by vhanla** [comment]
`aeTabIconX`, `aeTabIconXOver` TATTabElemType types draw before `aeTabActive`, so they won't show, and as you can see in the pictures below, close button is showing but only because I'm using a semi transparent PNG file, so it shows behind with dimmed color, the close button's `x` symbol should be white, not gray.

![image](https://user-images.githubusercontent.com/1015823/40816228-59923b8c-6511-11e8-8972-9ceb6c224fcb.png)
![image](https://user-images.githubusercontent.com/1015823/40816240-6de26b34-6511-11e8-8531-3ce79f8086cd.png)

A "hacky" workaround would be to draw only the surrounding area without overriding close button area as for now, but I guess it would be better to rearrange the order of those TATTabElemType elements drawing order.

**Comment by Alexey-T** [comment]
@vhanla fixed! demo shows customdraw tabs on bottom, and they paint BG and X mark.

**Comment by Alexey-T** [comment]
no updates?
